import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:expenloga_app/category.dart';
import 'package:expenloga_app/database_stuff/blueprint.dart';
import 'package:path_provider/path_provider.dart';

part 'database.g.dart';

@DriftDatabase(tables: [ExpensePrint, CategoryPrint])
//derived the name GeneratedDatabase by my self, that's because it was generated by drift afterwards
class DataBase extends _$DataBase {
  DataBase([QueryExecutor? executor]) : super(executor ?? _openConnection());

  @override
  int get schemaVersion => 1;

  static QueryExecutor _openConnection() {
    return driftDatabase(
      name: 'my_database',
      native: const DriftNativeOptions(
        // By default, `driftDatabase` from `package:drift_flutter` stores the
        // database files in `getApplicationDocumentsDirectory()`.
        databaseDirectory: getApplicationSupportDirectory,
      ),
      // If you need web support, see https://drift.simonbinder.eu/platforms/web/
    );
  }

  // future based function
  Future<int> expenseDataBase(
    String name,
    String comment,
    String date,
    String? imagePath,
    int price,
    int? categoryID,
  ) async {
    return await into(expensePrint).insert(
      ExpensePrintCompanion(
        namePrint: Value(name),
        commentPrint: Value(comment),
        datePrint: Value(date),
        imagePathPrint: Value(imagePath),
        pricePrint: Value(price),
        categoryIDPrint: Value(categoryID),
      ),
    );
  }

  Future<int> catDataBase(String title, String iconKey) async {
    return await into(categoryPrint).insert(
      CategoryPrintCompanion(
        titlePrint: Value(title),
        iconKeyPrint: Value(iconKey),
      ),
    );
  }

  // ADDED: The read pipeline function to fetch data from the database
  Future<List<ExpensePrintData>> getStoredExpenses() async {
    return await select(expensePrint).get();
  }
}
